# Generated by Django 3.1.6 on 2021-03-28 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(blank=True, null=True, upload_to='img')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='img')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='img')),
                ('img4', models.ImageField(blank=True, null=True, upload_to='img')),
                ('img5', models.ImageField(blank=True, null=True, upload_to='img')),
                ('video', models.FileField(blank=True, null=True, upload_to='video')),
                ('name', models.CharField(max_length=100)),
                ('des', models.TextField()),
                ('about_payment', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('phone2', models.CharField(blank=True, max_length=15, null=True)),
                ('province', models.CharField(choices=[('Punjab', 'Punjab'), ('Sindh', 'Sindh'), ('KP', 'KP'), ('Balochistan', 'Balochistan'), ('Islamabad', 'Islamabad')], max_length=20)),
                ('city', models.CharField(max_length=45)),
                ('address', models.TextField()),
            ],
        ),
    ]
