# Generated by Django 3.1.6 on 2021-03-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='solved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='varified',
            field=models.BooleanField(default=False),
        ),
    ]
